import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

import { loadReportLogoDataUrl } from "./memberStatementPdf";

export type DashboardCell = string | number;

export interface DashboardSection {
    title: string;
    head: string[];
    rows: DashboardCell[][];
}

export interface DashboardExportPayload {
    tenantName: string;
    generatedBy: string;
    sections: DashboardSection[];
}

function stamp() {
    return new Date().toISOString().slice(0, 10);
}

function triggerDownload(blob: Blob, filename: string) {
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
}

function escapeHtml(value: DashboardCell) {
    return String(value)
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;");
}

// Excel opens an HTML table saved as .xls natively, preserving the multi-block
// layout and header shading — no third-party library required.
export function downloadDashboardExcel(payload: DashboardExportPayload) {
    const tables = payload.sections.map((section) => {
        const headCells = section.head.map((cell) => `<th style="background:#0a0573;color:#fff;border:1px solid #999;padding:4px 8px;text-align:left">${escapeHtml(cell)}</th>`).join("");
        const bodyRows = section.rows.map((row) => {
            const cells = row.map((cell) => {
                const isNumber = typeof cell === "number";
                const align = isNumber ? "right" : "left";
                const value = isNumber ? cell : escapeHtml(cell);
                return `<td style="border:1px solid #ccc;padding:4px 8px;text-align:${align}">${value}</td>`;
            }).join("");
            return `<tr>${cells}</tr>`;
        }).join("");

        return `
            <table style="border-collapse:collapse;margin-bottom:18px">
                <tr><th colspan="${section.head.length}" style="background:#0f172a;color:#fff;border:1px solid #999;padding:6px 8px;text-align:left;font-size:14px">${escapeHtml(section.title)}</th></tr>
                <tr>${headCells}</tr>
                ${bodyRows}
            </table>`;
    }).join("");

    const html = `<html xmlns:x="urn:schemas-microsoft-com:office:excel"><head><meta charset="utf-8"></head><body>
        <h2>${escapeHtml(payload.tenantName)} — SACCO Dashboard</h2>
        <p>Generated by ${escapeHtml(payload.generatedBy)} on ${new Date().toLocaleString("en-GB")}</p>
        ${tables}
    </body></html>`;

    triggerDownload(new Blob([html], { type: "application/vnd.ms-excel;charset=utf-8" }), `sacco-dashboard-${stamp()}.xls`);
}

export async function downloadDashboardPdf(payload: DashboardExportPayload) {
    const doc = new jsPDF({ orientation: "portrait", unit: "pt", format: "a4" });
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 36;

    const primary: [number, number, number] = [10, 5, 115];
    const accent: [number, number, number] = [31, 168, 230];
    const text: [number, number, number] = [15, 23, 42];
    const muted: [number, number, number] = [71, 85, 105];

    const logoDataUrl = await loadReportLogoDataUrl();

    doc.setFillColor(...primary);
    doc.rect(0, 0, pageWidth, 80, "F");
    doc.setFillColor(...accent);
    doc.rect(0, 70, pageWidth, 8, "F");

    if (logoDataUrl) {
        try {
            doc.addImage(logoDataUrl, "PNG", margin, 16, 30, 30);
        } catch {
            // ignore logo decode failures
        }
    }

    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.text(payload.tenantName, margin + 40, 32, { maxWidth: pageWidth / 2 });
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text("SACCO Financial Dashboard", margin + 40, 50);
    doc.text(`Generated: ${new Date().toLocaleString("en-GB")}`, pageWidth - margin, 32, { align: "right" });
    doc.text(`By: ${payload.generatedBy}`, pageWidth - margin, 50, { align: "right" });

    let cursorY = 104;

    payload.sections.forEach((section) => {
        doc.setTextColor(...text);
        doc.setFont("helvetica", "bold");
        doc.setFontSize(12);
        doc.text(section.title, margin, cursorY);
        cursorY += 6;

        autoTable(doc, {
            startY: cursorY,
            head: [section.head],
            body: section.rows.map((row) => row.map((cell) => (typeof cell === "number" ? cell.toLocaleString("en-US") : cell))),
            theme: "grid",
            headStyles: { fillColor: primary, textColor: 255, fontStyle: "bold" },
            styles: { font: "helvetica", fontSize: 8.5, cellPadding: 5, textColor: text },
            alternateRowStyles: { fillColor: [248, 250, 252] },
            columnStyles: section.head.length > 1
                ? { [section.head.length - 1]: { halign: "right" } }
                : {},
            margin: { left: margin, right: margin }
        });

        cursorY = (doc as jsPDF & { lastAutoTable?: { finalY?: number } }).lastAutoTable?.finalY || cursorY;
        cursorY += 22;
    });

    const pages = doc.getNumberOfPages();
    for (let page = 1; page <= pages; page += 1) {
        doc.setPage(page);
        doc.setFont("helvetica", "normal");
        doc.setFontSize(8.5);
        doc.setTextColor(...muted);
        doc.text(`${payload.tenantName} • SACCO Dashboard • Page ${page} of ${pages}`, pageWidth / 2, pageHeight - 18, { align: "center" });
    }

    doc.save(`sacco-dashboard-${stamp()}.pdf`);
}
